# Generated by Django 3.2.9 on 2023-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='businesses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
