# Generated by Django 3.2.9 on 2023-11-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20231119_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='businesses',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_business_member',
            field=models.BooleanField(default=False),
        ),
    ]
