# Generated by Django 3.2.9 on 2023-12-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businessmemberanalytics_businessprofileanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmemberanalytics',
            name='converted_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businessmemberanalytics',
            name='leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businessprofileanalytics',
            name='converted_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businessprofileanalytics',
            name='leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businessprofileanalytics',
            name='team_members',
            field=models.IntegerField(default=0),
        ),
    ]
