# Generated by Django 3.2.9 on 2023-12-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20231211_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessleads',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='business.businessmember'),
        ),
    ]
