BUSINESS_LEAD_FIELDS = [
    {
        "name": "first_name",
        "default": True,
        "unique": False,
        "type": "text",
        "required": True,
        "is_active": True,
        "hidden_field": False,
        "default_value": "",
        "key": "first_name",
        "label": "Enter contact's first name",
        "placeholder": "Enter contact's first name",
        "label_key": "",
        "options": [],
        "min_length": 5,
        "max_length": 50,
        # "verify_object": False,
        # "verifiable_field": ""
    },
    {
        "name": "last_name",
        "default": True,
        "unique": False,
        "type": "text",
        "required": True,
        "is_active": True,
        "hidden_field": False,
        "default_value": "",
        "key": "last_name",
        "label": "Enter contact's last name",
        "placeholder": "Enter contact's last name",
        "label_key": "",
        "options": [],
        "min_length": 5,
        "max_length": 50,
        # "verify_object": False,
        # "verifiable_field": ""
    },
    {
        "name": "email",
        "default": True,
        "unique": False,
        "type": "text",
        "required": True,
        "is_active": True,
        "hidden_field": False,
        "default_value": "",
        "key": "email",
        "label": "Enter contact's email address",
        "placeholder": "Enter contact's email address",
        "label_key": "",
        "options": [],
        "min_length": 5,
        "max_length": 50,
        # "verify_object": False,
        # "verifiable_field": ""
    },
    {
        "name": "phone",
        "default": True,
        "unique": False,
        "type": "text",
        "required": True,
        "is_active": True,
        "hidden_field": False,
        "default_value": "",
        "key": "phone",
        "label": "Enter contact's phone number",
        "placeholder": "Enter contact's phone number",
        "label_key": "",
        "options": [],
        "min_length": 11,
        "max_length": 11,
        # "verify_object": False,
        # "verifiable_field": ""
    },
]